### ISSUE TITLE
Title: Initialize a React Application

### ISSUE THREAD

**Issue by kamal392** [kamal392/photo-port#1]
Body: User Stories

* As a user, I can see the About section.

* As a user, I can see the Navigation menu.

**Comment by kaushalpapnai** [comment]
I came across your project on GitHub and noticed the open issue . I'm interested in contributing to the project and would like to ask if this issue is still available for work.
I believe I can make a valuable contribution to this particular issue,  Could you please let me know if this issue is still open for contribution? If so, I would like to discuss the details and start working on it.
Looking forward to hearing from you!

**Comment by kamal392** [comment]
> I came across your project on GitHub and noticed the open issue . I'm interested in contributing to the project and would like to ask if this issue is still available for work. I believe I can make a valuable contribution to this particular issue, Could you please let me know if this issue is still open for contribution? If so, I would like to discuss the details and start working on it. Looking forward to hearing from you!

Hi, Thanks for reaching me out for this open issue . This issue is a part of my school work . which I had completed already .
thank you once again .
